import {
  IconCamera,
  IconChartBar,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronsLeft,
  IconChevronsRight,
  IconCircleCheckFilled,
  IconCirclePlusFilled,
  IconCreditCard,
  IconDashboard,
  IconDatabase,
  IconDots,
  IconDotsVertical,
  IconFileAi,
  IconFileDescription,
  IconFileWord,
  IconFolder,
  IconGripVertical,
  IconHelp,
  IconInnerShadowTop,
  IconLayoutColumns,
  IconListDetails,
  IconLoader,
  IconLogout,
  IconMail,
  IconNotification,
  IconPlus,
  IconReport,
  IconSearch,
  IconSettings,
  IconShare3,
  IconTrash,
  IconTrendingDown,
  IconTrendingUp,
  IconUserCircle,
  IconUsers,
  type Icon,
} from '@tabler/icons-react';

export const Icons = {
  camera: IconCamera,
  chartBar: IconChartBar,
  chevronDown: IconChevronDown,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  chevronsLeft: IconChevronsLeft,
  chevronsRight: IconChevronsRight,
  circleCheckFilled: IconCircleCheckFilled,
  circlePlusFilled: IconCirclePlusFilled,
  creditCard: IconCreditCard,
  dashboard: IconDashboard,
  database: IconDatabase,
  dots: IconDots,
  dotsVertical: IconDotsVertical,
  fileAi: IconFileAi,
  fileDescription: IconFileDescription,
  fileWord: IconFileWord,
  folder: IconFolder,
  gripVertical: IconGripVertical,
  help: IconHelp,
  innerShadowTop: IconInnerShadowTop,
  layoutColumns: IconLayoutColumns,
  listDetails: IconListDetails,
  loader: IconLoader,
  logout: IconLogout,
  mail: IconMail,
  notification: IconNotification,
  plus: IconPlus,
  report: IconReport,
  search: IconSearch,
  settings: IconSettings,
  share3: IconShare3,
  trash: IconTrash,
  trendingDown: IconTrendingDown,
  trendingUp: IconTrendingUp,
  userCircle: IconUserCircle,
  users: IconUsers,
};

export type IconKey = keyof typeof Icons;
export { type Icon };
